set guioptions-=T  " hide toolbar
set guioptions+=Rr " Turn on scroll bars

if has("gui_macvim")
  " macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>

  set transparency=12

  " Fullscreen takes up entire screen
  set fuoptions=maxhorz,maxvert

  "Mac OS X style command line editing
  cnoremap <A-Backspace> <C-W>
  cnoremap <D-Backspace> <C-U>

  " Command-/ to toggle comments
  map <D-/> <plug>NERDCommenterToggle
  imap <D-/> <Esc><plug>NERDCommenterToggle i

  " Command-T (a la Textmate)
  macmenu &File.New\ Tab key=<nop>
  map <D-t> :CommandT<CR>
  imap <D-t> <Esc>:CommandT<CR>
end

" Source vimrc after saving it
autocmd! BufWritePost .gvimrc,gvimrc source $MYGVIMRC
autocmd! BufWritePost .vimrc,vimrc source $MYVIMRC | source $MYGVIMRC | NERDTreeToggle | NERDTreeToggle

