set guioptions-=T  " hide toolbar
set guioptions+=Rr " Turn on scroll bars

if has("gui_macvim")
  set transparency=7

  " Fullscreen takes up entire screen
  set fuoptions=maxhorz,maxvert

  "Mac OS X style command line editing
  cnoremap <A-Backspace> <C-W>
  cnoremap <D-Backspace> <C-U>

  " Command-/ to toggle comments
  map  <D-/> ,/
  imap <D-/> ,/
  vmap <D-/> ,/
end

" Source vimrc after saving it
autocmd! BufWritePost .gvimrc,gvimrc source $MYGVIMRC
autocmd! BufWritePost .vimrc,vimrc source $MYVIMRC | source $MYGVIMRC | NERDTreeToggle | NERDTreeToggle

