#!/bin/sh

# See http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

new_tags_file="`mktemp -t ctags`"
ctags --tag-relative -Rf "${new_tags_file}" --exclude=.git --languages=-javascript,sql
mv "$new_tags_file" ".git/tags"

