export CURRENT_SHELL="zsh"
export DOT_FILES=$(dirname $(dirname $(readlink $HOME/.zshrc)))

# Install and load oh-my-zsh
source $DOT_FILES/zsh/oh-my-zsh.zsh

# Common functionality between Zsh and Bash
source $DOT_FILES/shell/common.sh

for file in $(ls -1 $DOT_FILES/zsh/lib/*.zsh); do
  source $file
done

# Tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator
alias tmuxinator='rvm default exec tmuxinator'

# RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
rvm default

