export DOT_FILES=$HOME/.config
export CURRENT_SHELL=`which zsh`

# Include some ZSH-compatible config from bash (such as aliases, etc)
source $DOT_FILES/bash/common

# Install and load oh-my-zsh
source $DOT_FILES/zsh/oh-my-zsh

# Extra ZSH configuration
source $DOT_FILES/zsh/config

# My custom theme
source $DOT_FILES/zsh/theme
