
export DOT_FILES=$HOME/.config
source $DOT_FILES/bash/common
source $DOT_FILES/git/git-completion
source $DOT_FILES/bash/save-directory


if [ $system_name == 'Darwin' ]; then
  source $DOT_FILES/ruby/gemdoc
  source $DOT_FILES/bash/terminal
else
  if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  else
    . $DOT_FILES/bash/bash_completion
  fi
fi

export PS1=' [`pwd`$(__git_ps1 " \[${COLOR_RED}\](%s)\[${COLOR_NC}\]")]\n$ '

function __pair_status {
  hitchstatus " %s";
}

# readline settings
bind "set completion-ignore-case on" 
bind "set bell-style none" # No bell, because it's damn annoying
bind "set show-all-if-ambiguous On" # this allows you to automatically show completion without double tab-ing

shopt -s checkwinsize
shopt -s histappend
shopt -s globstar 2>/dev/null # Bash 4 and above only

complete -C $DOT_FILES/bash/rake-completion.rb -o default rake}