export CURRENT_SHELL="bash"
export DOT_FILES=$HOME/.config

# All things that are both ZSH and Bash compatible
source $DOT_FILES/shell/common.sh

# Git completion support in bash
source $DOT_FILES/git/git-completion

# RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
